# Generated by Django 3.1.2 on 2020-11-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_statment_paycheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gym',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
